### ISSUE TITLE
fractional values in polling_interval and delay

### ISSUE THREAD

**Issue by DiFuks** [wechuli/allcheckspassed#5]
Please add the ability to specify fractional values in polling_interval and delay. For example, 0.5. [Currently, the function parseInt is used](https://github.com/wechuli/allcheckspassed/blob/884b1e421bece4462a09263cb97a634f2a2e224f/src/utils/inputsExtractor.ts#L50), which converts 0.5 to 0. It can be replaced with parseFloat or Number.

**Comment by wechuli** [comment]
Sounds like a reasonable proposal, will look at it over the weekend.
